scrape_configs:
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:9091']
        labels:
          application: 'product-service'
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:9093']
        labels:
          application: 'user-service'
  - job_name: 'order'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:9092']
        labels:
          application: 'order'